name: Frontend CI

on:
  push:
    branches: [ main ]
  pull_request:
     branches: [main]

jobs:
  frontend:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout code
      - name: Checkout code
        uses: actions/checkout@v4

      # 2. Setup Node.js with caching
      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 20
 

          cache: npmi 
          cache-dependency-path: frontend/package-lock.json

      # 3. Install dependencies
      - name: Install dependencies
        run: npm ci
        working-directory: frontend

      # 4. Lint
      - name: Run ESLint
        run: npm run lint
        working-directory: frontend

      # 5. Test
      - name: Run tests
        run: npm run test -- --run
        working-directory: frontend

      # 6. Build
      - name: Build app
        run: npm run build
        working-directory: frontend

      # 7. Save the build
      - name: Upload build artifact
        uses: actions/upload-artifact@v4
        with:
          name: frontend-dist
          path: frontend/dist/
